### ISSUE TITLE
login

### ISSUE THREAD

**Issue by kraccoon-dev** [Dot-Line-20/glint-server#11]
jwt를 이용한 로그인 시스템 구현입니다.
access token과 refresh token의 만료일은 각각 1h, 90d입니다.
리뷰에선 전체 코드를 검토하지 않고 테스트코드를 통해 진행할것입니다.

**Comment by H2Owater425** [comment]
JWT의 암호화 알고리즘은 어떻게 할까요?

**Comment by kraccoon-dev** [comment]
> JWT의 암호화 알고리즘은 어떻게 할까요?

sha256을 사용해주세요.

**Comment by H2Owater425** [comment]
[rfc7518(JSON Web Algorithms)](https://datatracker.ietf.org/doc/html/rfc7518)에는 SHA256 연산을 이용하는 해시 알고리즘으로는 HMAC을 사용한 HS256과 P256과 ECDSA를 이용한 ES256이 있는데 둘중 무엇을 사용하여야 할까요?

**Comment by kraccoon-dev** [comment]
> [rfc7518(JSON Web Algorithms)](https://datatracker.ietf.org/doc/html/rfc7518)(3.1)에 명시되어있는 SHA256 연산을 이용하는 해시 알고리즘으로는 HMAC을 사용한 HS256과 P256과 ECDSA를 이용한 ES256이 있는데 둘중 무엇을 사용하여야 할까요?

jsonwebtoken의 default알고리즘인 HMAC SHA256을 사용하겠습니다.

**Comment by H2Owater425** [comment]
JWT 생성 및 인증 라이브러리 정도는 만들어서 사용하려 하는데 괜찮을까요?

**Comment by kraccoon-dev** [comment]
@H2Owater425 굳이 만들어야하는 이유가 있나요?

**Comment by H2Owater425** [comment]
굳이 찾아보자면 페키지 사이즈와 저희 코드에 특화된 기능 등이 있지만, 이유가 그렇게 크지는 않은 것 같습니다.
원하신다면 npm에 올라와있는 [jsonwebtoken](https://www.npmjs.com/package/jsonwebtoken)을 사용하겠습니다.

**Comment by kraccoon-dev** [comment]
@H2Owater425 큰 이유가 없다면 기존 jsonwebtoken을 사용해 주세요

**Comment by H2Owater425** [comment]
계정은 이메일로 찾으면 될까요?

**Comment by kraccoon-dev** [comment]
> 계정은 이메일로 찾으면 될까요?

계정 찾기는 #13 을 참고해주세요.
